import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getLeagueBrand } from '../../lib/branding'
import { scopedTable } from '../../lib/leagueClient'
import { getCourseHoleGuide, getEventPlayers, getEventQuestions, getEventParticipants, getEventScores, getLeagueEvent, type EventPlayer, type EventQuestion, type EventParticipant, type EventRow, type EventScore } from '../../lib/eventQueries'
import { scoreEvent } from '../../lib/eventScoring'
import BulkEventScoreInput from '../../components/admin/BulkEventScoreInput'
import EventResolutionStatus from '../../components/admin/EventResolutionStatus'

const labels: Record<string, string> = { draft: 'Luonnos', betting_open: 'Veikkaukset auki', betting_closed: 'Veikkaukset suljettu', scoring: 'Tulosten syöttö', results_ready: 'Tulokset valmiit', presented: 'Esitetty' }
const nextStatus: Record<string, { label: string; status: string }> = { draft: { label: 'Avaa veikkausmarkkina', status: 'betting_open' }, betting_open: { label: 'Sulje veikkausmarkkina', status: 'betting_closed' }, betting_closed: { label: 'Siirry tulosten syöttöön', status: 'scoring' }, results_ready: { label: 'Merkitse esitetyksi', status: 'presented' } }

export default function AdminEventDetail() {
  const { id } = useParams<{ id: string }>()
  const [event, setEvent] = useState<EventRow | null>(null); const [players, setPlayers] = useState<EventPlayer[]>([]); const [questions, setQuestions] = useState<EventQuestion[]>([]); const [participants, setParticipants] = useState<EventParticipant[]>([]); const [scores, setScores] = useState<EventScore[]>([]); const [courseHoles, setCourseHoles] = useState<Array<{ hole: number; par: number }>>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [selectedPlayer, setSelectedPlayer] = useState<string | null>(null); const [points, setPoints] = useState(''); const [strokes, setStrokes] = useState(''); const [holePoints, setHolePoints] = useState(''); const [paste, setPaste] = useState('')
  const reload = useCallback(async () => { if (!id) return; const [e, p, q, part, s] = await Promise.all([getLeagueEvent(id), getEventPlayers(id), getEventQuestions(id), getEventParticipants(id), getEventScores(id)]); const holes = e.course_id ? await getCourseHoleGuide(e.course_id) : []; setEvent(e); setPlayers(p); setQuestions(q); setParticipants(part); setScores(s); setCourseHoles(holes); setLoading(false) }, [id])
  useEffect(() => { reload().catch(() => setLoading(false)) }, [reload])
  useEffect(() => {
    if (event?.status !== 'betting_open') return
    const timer = window.setInterval(() => { reload().catch(() => undefined) }, 30_000)
    return () => window.clearInterval(timer)
  }, [event?.status, reload])
  const submitted = useMemo(() => new Map(scores.map(s => [s.player_id, s])), [scores])
  if (loading || !event) return <div className="text-gray-400">Ladataan...</div>
  const currentEvent = event
  const url = `${window.location.origin}/bet/${event.betting_url_token}`
  async function transition(status: string) { setBusy(true); await scopedTable('league_events').update({ status }).eq('id', currentEvent.id); await reload(); setBusy(false) }
  async function saveScore() {
    if (!selectedPlayer || !points) return
    setBusy(true); const existing = submitted.get(selectedPlayer); const { data, error } = await scopedTable('event_scores').upsert({ ...(existing ? { id: existing.id } : {}), event_id: currentEvent.id, player_id: selectedPlayer, total_points: Number(points), total_strokes: strokes ? Number(strokes) : null, is_corrected: !!existing }, { onConflict: 'event_id,player_id' }).select().single()
    if (!error && data) { const scoreId = (data as any).id; const values = holePoints.split(',').map(v => Number(v.trim())).filter(v => Number.isFinite(v)).slice(0, 18).map((points, i) => ({ event_score_id: scoreId, hole: i + 1, points })); if (values.length) await scopedTable('event_hole_results').upsert(values, { onConflict: 'event_score_id,hole' }); if (existing) await scoreEvent(currentEvent.id); setMessage(existing ? 'Tulokset laskettu uudelleen' : 'Tulos tallennettu'); await reload() } else setMessage(error?.message ?? 'Tallennus epäonnistui'); setBusy(false)
  }
  function parsePaste() {
    const row = paste.split('\n').map(line => line.split(/[,;\t]/).map(v => v.trim())).find(columns => columns.length >= 2 && Number.isFinite(Number(columns[1])))
    if (!row) { setMessage('Liitä rivejä muodossa pelaaja, pisteet, lyönnit'); return }
    const player = players.find(({ player }) => player.full_name.toLowerCase() === row[0].toLowerCase())
    if (player) setSelectedPlayer(player.player_id)
    setPoints(row[1] ?? ''); setStrokes(row[2] ?? ''); setMessage('CSV-rivi tunnistettu — tarkista ja tallenna')
  }
  return <div className="max-w-5xl space-y-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link to="/admin/events" className="text-xs text-gray-500 hover:text-white">← Tapahtumat</Link><h1 className="text-3xl font-bold text-white mt-2">{event.name}</h1><p className="text-sm text-gray-500 mt-1">{new Date(`${event.event_date}T00:00:00`).toLocaleDateString('fi-FI')}{event.course?.name && ` · ${event.course.name}`}</p></div><span className="bg-white/10 text-gray-300 text-sm px-3 py-1.5 rounded-full">{labels[event.status]}</span></div>
    {message && <div className="rounded-lg bg-gc-green/10 border border-gc-green/30 text-gc-green p-3 text-sm">{message}</div>}
    <section className="card p-5 space-y-4"><div><h2 className="text-white font-bold">Veikkauksen tila</h2><p className="text-sm text-gray-500 mt-1">{event.status === 'draft' ? 'Veikkausmarkkina on suljettu. Avaa se, kun tapahtuma on valmis osallistujille.' : event.status === 'betting_open' ? 'Veikkausmarkkina on avoinna osallistujille.' : `Veikkaukset on suljettu · ${labels[event.status].toLowerCase()}.`}</p></div><div className="grid grid-cols-2 gap-3 border-y border-white/5 py-4 sm:grid-cols-4"><div><div className="label mb-1">Päivä</div><div className="text-sm text-white">{new Date(`${event.event_date}T00:00:00`).toLocaleDateString('fi-FI')}</div></div><div><div className="label mb-1">Kenttä</div><div className="text-sm text-white">{event.course?.name ?? 'Ei valittu'}</div></div><div><div className="label mb-1">Pelaajat</div><div className="text-sm text-white">{players.length}</div></div><div><div className="label mb-1">Kysymykset</div><div className="text-sm text-white">{questions.length}</div></div><div className="col-span-2 sm:col-span-4"><div className="label mb-1">Osallistujakoodi</div>{event.participant_code ? <div className="flex flex-wrap items-center gap-2"><code className="rounded bg-black/20 px-2 py-1 font-mono text-sm text-white">{event.participant_code}</code><button type="button" onClick={() => navigator.clipboard?.writeText(event.participant_code ?? '')} className="btn-ghost px-2 py-1 text-xs">Kopioi koodi</button></div> : <div className="text-sm text-gray-500">Ei asetettu</div>}</div></div>{nextStatus[event.status] && <button disabled={busy} onClick={() => transition(nextStatus[event.status].status)} className="btn-primary px-4 py-2 disabled:opacity-40">{nextStatus[event.status].label}</button>}{event.status === 'results_ready' && <Link to={`/bet/${event.betting_url_token}`} className="btn-ghost inline-block ml-2 px-4 py-2">Avaa tulokset</Link>}<div className="flex flex-wrap items-center gap-2 text-xs text-gray-500 pt-2"><code className="bg-black/20 rounded px-2 py-1">{url}</code><button onClick={() => navigator.clipboard?.writeText(url)} className="btn-ghost px-2 py-1">Kopioi linkki</button>{event.status !== 'draft' && <span>{participants.length} pelaajaa veikannut</span>}</div></section>
    <EventResolutionStatus players={players} questions={questions} scores={scores} />
    {event.status === 'scoring' || event.status === 'results_ready' ? <><BulkEventScoreInput event={currentEvent} players={players} scores={scores} courseHoles={courseHoles} onReload={reload} /><section className="card p-5 space-y-5"><div><h2 className="text-white font-bold">Yksittäinen tulos</h2><p className="text-xs text-gray-500 mt-1">Varasyöttö yhdelle pelaajalle. Bulk-kortit kannattaa kirjata yllä.</p><textarea value={paste} onChange={e => setPaste(e.target.value)} placeholder="Liitä LLM:n CSV-vastaus tähän" className="w-full input min-h-20 mt-2" /><button type="button" onClick={parsePaste} className="btn-ghost text-xs px-3 py-1.5 mt-2">Tarkista CSV</button></div><div className="grid sm:grid-cols-2 gap-2">{players.map(({ player }) => { const score = submitted.get(player.id); const selected = selectedPlayer === player.id; return <button key={player.id} onClick={() => { setSelectedPlayer(player.id); setPoints(score?.total_points?.toString() ?? ''); setStrokes(score?.total_strokes?.toString() ?? ''); setHolePoints(score?.holes?.map(h => h.points).join(', ') ?? '') }} className={`text-left rounded-lg border px-3 py-2 transition-colors ${selected ? 'border-gc-green bg-gc-green/20 ring-1 ring-gc-green/40' : score ? 'border-gc-green/60 bg-gc-green/10 shadow-[0_0_0_1px_rgba(34,197,94,0.12)]' : 'border-white/10 bg-white/[0.02]'}`}><span className="flex items-center gap-2 text-white"><span className={score ? 'text-gc-green' : 'text-gray-300'}>{score ? '✓' : '○'}</span><span>{player.full_name}</span>{score && <span className="rounded-full bg-gc-green/20 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide text-gc-green">Tallennettu</span>}</span><span className={`block ml-6 text-xs ${score ? 'font-medium text-gc-green' : 'text-gray-500'}`}>{score ? `${score.total_points}p${score.total_strokes != null ? ` · ${score.total_strokes} lyöntiä` : ''}` : 'ei vielä'}</span></button> })}</div>{selectedPlayer && <div className="grid sm:grid-cols-3 gap-3 border-t border-white/5 pt-4"><label><span className="label block mb-1 text-xs">Pisteet *</span><input type="number" value={points} onChange={e => setPoints(e.target.value)} className="w-full input" /></label><label><span className="label block mb-1 text-xs">Lyönnit</span><input type="number" value={strokes} onChange={e => setStrokes(e.target.value)} className="w-full input" /></label><label className="sm:col-span-3"><span className="label block mb-1 text-xs">Reikäpisteet (1–18, pilkuilla)</span><input value={holePoints} onChange={e => setHolePoints(e.target.value)} placeholder="2, 3, 1, ..." className="w-full input" /></label><button disabled={busy || !points} onClick={saveScore} className="btn-primary px-4 py-2 disabled:opacity-40">{submitted.has(selectedPlayer) ? 'Korjaa tulos' : 'Tallenna tulos'}</button></div>}</section></> : null}
    <section className="card p-5"><h2 className="text-white font-bold mb-3">Osallistujat</h2>{event.status === 'draft' ? <p className="text-sm text-gray-500">Osallistujat näkyvät, kun veikkaukset avataan.</p> : participants.length === 0 ? <p className="text-sm text-gray-500">Ei vielä veikkaajia</p> : <div className="divide-y divide-white/5">{participants.map(p => <div key={p.id} className="flex gap-3 py-2 text-sm"><span className="text-white flex-1">{p.display_name}</span><span className="text-gray-500">{p.emoji_pin ?? '—'}</span><span className="text-gray-500">{p.total_points_awarded}p</span></div>)}</div>}</section>
    <section className="card p-5"><h2 className="text-white font-bold mb-3">Kysymykset</h2><div className="space-y-2">{questions.map((q, i) => <div key={q.id} className="flex gap-3 text-sm border-b border-white/5 py-2 last:border-0"><span className="text-gray-500">{i + 1}</span><span className="text-white flex-1">{q.question_type.display_name}</span>{event.status === 'results_ready' && <code className="text-xs text-gc-green">{JSON.stringify(q.correct_answer)}</code>}</div>)}</div></section>
    <p className="text-xs text-gray-600">Liigan brändi: {getLeagueBrand().name}</p>
  </div>
}
